apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m2q7k4kyu-go
  janus-idp.io/tekton: m2q7k4kyu-go
  backstage.io/kubernetes-id: m2q7k4kyu-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m2q7k4kyu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
