apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m2q7k4kyu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m2q7k4kyu-go 
  name: m2q7k4kyu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m2q7k4kyu-go 
